name: Deploy

on:
  workflow_run:
    workflows:
      - Build and Push Docker image to GHCR
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'

    runs-on:
      - self-hosted

    steps:
      - name: Pull latest image
        run: |
          cd /home/saman/Desktop/test/hello-server

          docker compose pull

      - name: Restart containers
        run: |
          cd /home/saman/Desktop/test/hello-server

          docker compose up -d

      - name: Remove dangling images
        run: docker image prune -f